name: Mortality
version: 1.0.0
main: io.github.black_Kittys22.mortality.Main
api-version: "1.21"
author: black_Kittys

softdepend: [WorldEdit, Protcollib]

commands:
  sethearts:
    description: Setzt die Herzen eines bestimmten Spielers.
    permission: heartsystem.set
    usage: /sethearts <Spieler> <Anzahl>

  settings:
    description: Öffnet das Einstellungsmenü
    usage: /settings

  resetworld:
     description: Setzt den Zustand der Weltherzen komplett zurück

  setsafezone:
     description: Setzt die Safe Zone für den Nether Heart Reset
     usage: /setsafezone <radius>
     permission: mortality.setsafezone




permissions:
  commandpickaxe.give:
    description: Erlaubt es, sich selbst die Spitzhacke zu geben
    default: op

  mortality.setsafezone:
    description: Erlaubt das Setzen der Safe Zone
    default: op

  commandpickaxe.give.others:
    description: Erlaubt es, anderen Spielern die Spitzhacke zu geben
    default: op

  commandpickaxe.bypass:
    description: Erlaubt das Abbauen von Command-Blöcken ohne Spitzhacke
    default: op
