name: Mortality
version: 1.2
main: io.github.black_Kittys22.mortality.Main
api-version: "1.21"
author: black_Kittys

softdepend: [WorldEdit, Protcollib]

commands:
  sethearts:
    description: Setzt die Herzen eines bestimmten Spielers.
    permission: heartsystem.set
    usage: /sethearts <Spieler> <Anzahl>

  settings:
    description: Öffnet das Einstellungsmenü
    usage: /settings

  heartcolor:
    description: Ändert die Herzfarbe auf dem Server
    usage: /heartcolor <farbe>
    permission: heartsystem.color